### local pv
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: jenkins
#   labels:
#     type: local
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 5Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: /var/lib/data

### Pod on pv
# apiVersion: v1
# kind: Pod
# metadata:
#   name: test-pd
# spec:
#   containers:
#   - image: k8s.gcr.io/test-webserver
#     name: test-container
#     volumeMounts:
#     - mountPath: /jenkins
#       name: jenkins
#   volumes:
#   - name: jenkins
#     # This GCE PD must already exist.
#     gcePersistentDisk:
#       pdName: jenkins
#       fsType: ext4

### gce disk 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteOnce
  gcePersistentDisk:
    pdName: jenkins
    fsType: ext4