### gce disk 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteOnce
  gcePersistentDisk:
    pdName: jenkins
    fsType: ext4
